language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=django==1.4
  - DJANGO=django==1.5
  - DJANGO=django==1.6
  - DJANGO=django==https://www.djangoproject.com/download/1.7c1/tarball/
# command to install dependencies
# unittest2 should be only installed for python 2.6
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi  
  - pip install $DJANGO
  - "pip install -r requirements.txt"
# command to run tests
script: python tests.py
