language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
# command to install dependencies
install: 
  - pip install django==$DJANGO
  - "pip install -r requirements.txt"
# command to run tests
script: python tests.py